### ISSUE TITLE
Using requestAnimationFrame loses time

### ISSUE THREAD

**Issue by u01jmg3** [fengyuanchen/vue-countdown#43]
When comparing a 7 minute countdown timer with a physical stopwatch, this library loses around a second a minute resulting in a loss of ~7 seconds.

The same applies when using the `setTimeout()` fallback although over 7 minutes the countdown timer only loses ~2 seconds.

Is there anyway to compensate for this drift? I am using the countdown timer for examinations (in an iOS app) which must allow a student exactly 7 minutes to a complete a task.

---

It looks like [this line here](https://github.com/fengyuanchen/vue-countdown/blob/master/src/index.js#L247) contributes to the loss of time because `timestamp - start` may be (marginally) greater than `delay` (`1000 ms`) and over time this builds up.

**Comment by fengyuanchen** [comment]
Good discovery. I will improve this soon.

**Comment by u01jmg3** [comment]
Thanks for making this change so quickly.

However, when comparing to various physical stopwatches over 7 minutes I am finding that the countdown \*still\* lags behind real time.

Have you tried this type of testing?

**Comment by fengyuanchen** [comment]
As a browser-side count down component, I think it is hard to be accurate as a physical stopwatch. I guess it may have a deviation of ±0.5s per minute (±8ms per step)  when using the `window.requestAnimationFrame` function.

**Comment by u01jmg3** [comment]
Do you think it would be a good idea to have a way of not using `window.requestAnimationFrame` (and instead defaulting to `setTimeout()`)?

**Comment by fengyuanchen** [comment]
@u01jmg3 See #33.

**Comment by klesun** [comment]
Hi. We observe that the library still produces a time error that becomes clearly noticeable after an hour of work, the error seems to depend on tab activity.

In my humble opinion the core of the timing issue is actually here:
```javascript
progress() {
  this.totalMilliseconds -= this.interval;
```

The library decrements the `totalMilliseconds` by a fixed interval value not accounting for the real time that tick took which [can be off](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#late_timeouts) from the requested time by few milliseconds depending on stuff like CPU load - those milliseconds slowly accumulate over time.

I think what would be conceptually correct here is:
```javascript
progress() {
    this.totalMilliseconds = this.endTime - Date.now();
```

That way we would eliminate the time error by making `totalMilliseconds` to get decremented by the effective time that tick took rather than the time that we requested from the unreliable OS.
